import streamlit as st
import pandas as pd
import json
from sqlalchemy import text
from scripts.database import engine
from scripts.ai_agent import trigger_semantic_router
from scripts.model_runtime import runtime
from scripts.statementScrape import run_etl_pipeline

# ==========================================
# 1. CORE FUNCTIONS
# ==========================================


def approve_ai_suggestion(
    ticket_id,
    bucket_name,
    new_keys,
    target_index=None,
    config_path="mapping_config.json",
):
    """
    Injects the AI's mathematically verified keys into the JSON config.
    """
    try:
        # 1. Load the current config
        with open(config_path, "r") as f:
            config = json.load(f)

        # 2. Convert the database string back into a Python list
        keys_to_add = json.loads(new_keys) if isinstance(new_keys, str) else new_keys
        target_map = config["normalized_indirect_cf_synonym_map"]

        if bucket_name in target_map:
            # 3. Inject the keys
            if target_index is not None and target_index != "Create New Group":
                # Append to a specific existing sub-array
                target_map[bucket_name][int(target_index)].extend(keys_to_add)
            else:
                # Create a brand new sub-array
                target_map[bucket_name].append(keys_to_add)

            # 4. Save the updated config back to disk
            with open(config_path, "w") as f:
                json.dump(config, f, indent=4)

            # 5. Close the loop: Mark the database ticket as APPROVED
            with engine.connect() as conn:
                conn.execute(
                    text(
                        'UPDATE ai_forensic_logs SET "Status" = \'APPROVED\' WHERE "TicketID" = :tid'
                    ),
                    {"tid": ticket_id},
                )
                conn.commit()
            return True, f"Successfully updated {bucket_name}"
        else:
            return False, f"Bucket {bucket_name} not found in config."

    except Exception as e:
        return False, str(e)


def load_config():
    with open("mapping_config.json", "r") as f:
        return json.load(f)


def run_local_ollama(keys):
    """
    Helper to mimic the local Ollama logic from the scraper loop.
    """
    runtime.load_models()
    ai_sorted_json = {}
    for key in keys:
        top_candidates = runtime.find_nearest_buckets(key)
        if top_candidates:
            result = runtime.process_with_phi3(key, top_candidates)
            if result:
                for bucket, k_list in result.items():
                    if bucket not in ai_sorted_json:
                        ai_sorted_json[bucket] = []
                    ai_sorted_json[bucket].extend(k_list)
    return ai_sorted_json


# ==========================================
# 2. STREAMLIT UI
# ==========================================

st.set_page_config(page_title="Financial ETL Control Center", layout="wide")

# --- UI Layout: Tabs ---
tab1, tab2 = st.tabs(["📋 Approval Queue", "🧪 AI Router Debugger"])

# ------------------------------------------
# TAB 1: AI Forensic Approval Queue
# ------------------------------------------
with tab1:
    st.title("AI Forensic Approval Queue")
    st.write("Review mathematically verified key mappings generated by the pipeline.")

    try:
        pending_logs = pd.read_sql(
            "SELECT * FROM ai_forensic_logs WHERE \"Status\" = 'PENDING'", engine
        )
    except Exception as e:
        st.error(f"Database Connection Error: {e}")
        pending_logs = pd.DataFrame()

    config = load_config()

    if not pending_logs.empty:
        for _, row in pending_logs.iterrows():
            with st.expander(
                f"Ticket: {row['Ticker']} - {row['LeakType']}", expanded=True
            ):
                # Layout data in columns for better readability
                col1, col2 = st.columns(2)
                with col1:
                    st.write(f"**Leak Amount:** `{row['LeakAmount']}`")
                    st.write(f"**Suggested Category:** `{row['SuggestedCategory']}`")
                with col2:
                    st.write(f"**Keys to Add:** `{row['MissingKeyFound']}`")

                st.info(f"**Reasoning:** {row['Reasoning']}")

                # Get the existing sub-arrays for this category to populate the dropdown
                category = row["SuggestedCategory"]
                existing_groups = config["normalized_indirect_cf_synonym_map"].get(
                    category, []
                )

                # Create a list of options for the user
                options = ["Create New Group"]
                for i, group in enumerate(existing_groups):
                    options.append(f"Append to Group {i}: {group}")

                # The dropdown selection
                selected_option = st.selectbox(
                    "Where should this key go?",
                    options,
                    key=f"select_{row['TicketID']}",
                )

                if st.button(
                    "Approve & Inject", key=f"btn_{row['TicketID']}", type="primary"
                ):
                    # Figure out the index based on the selection
                    target_index = (
                        None
                        if selected_option == "Create New Group"
                        else options.index(selected_option) - 1
                    )

                    success, msg = approve_ai_suggestion(
                        row["TicketID"], category, row["MissingKeyFound"], target_index
                    )
                    if success:
                        st.success(msg)
                        st.rerun()  # Refreshes the UI to clear the approved ticket
                    else:
                        st.error(msg)
    else:
        st.success("No pending AI suggestions. Everything is balanced!")


st.divider()
st.subheader("🚀 Run ETL Pipeline")

# Select the mode
selected_mode = st.radio(
    "Select AI Routing Engine:", ["Local (Ollama)", "Cloud (Gemini)"], horizontal=True
)

if st.button("Start ETL Batch", type="primary"):
    mode_param = "local" if "Local" in selected_mode else "cloud"

    with st.spinner(
        f"Running ETL Pipeline using {mode_param.upper()} AI... Check terminal for live logs."
    ):
        try:
            run_etl_pipeline(ai_mode=mode_param)
            st.success("ETL Batch Processing Complete!")
        except Exception as e:
            st.error(f"Pipeline crashed: {e}")
